// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx49TNPBE6taWebenDdLxMEShp-VLF3vw',
    appId: '1:351811632239:web:732fb03c982e65cc99e19a',
    messagingSenderId: '351811632239',
    projectId: 'matche-39f37',
    authDomain: 'matche-39f37.firebaseapp.com',
    storageBucket: 'matche-39f37.firebasestorage.app',
    measurementId: 'G-649KC39JRX',
    databaseURL: 'https://matche-39f37-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgDgmSvLiZA9XYTfE6SSinfd8KQ0QfN5s',
    appId: '1:351811632239:android:fa2df53656f5b28399e19a',
    messagingSenderId: '351811632239',
    projectId: 'matche-39f37',
    storageBucket: 'matche-39f37.firebasestorage.app',
    databaseURL: 'https://matche-39f37-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKUeM2GYoZxDy0Pj-Pghi-YnnYdXsvHjw',
    appId: '1:351811632239:ios:2e0e251b2249f03799e19a',
    messagingSenderId: '351811632239',
    projectId: 'matche-39f37',
    storageBucket: 'matche-39f37.firebasestorage.app',
    iosBundleId: 'com.example.matcha',
    databaseURL: 'https://matche-39f37-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKUeM2GYoZxDy0Pj-Pghi-YnnYdXsvHjw',
    appId: '1:351811632239:ios:2e0e251b2249f03799e19a',
    messagingSenderId: '351811632239',
    projectId: 'matche-39f37',
    storageBucket: 'matche-39f37.firebasestorage.app',
    iosBundleId: 'com.example.matcha',
    databaseURL: 'https://matche-39f37-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx49TNPBE6taWebenDdLxMEShp-VLF3vw',
    appId: '1:351811632239:web:6c18317221bcb76199e19a',
    messagingSenderId: '351811632239',
    projectId: 'matche-39f37',
    authDomain: 'matche-39f37.firebaseapp.com',
    storageBucket: 'matche-39f37.firebasestorage.app',
    measurementId: 'G-QKR8JQD8KL',
    databaseURL: 'https://matche-39f37-default-rtdb.firebaseio.com',
  );
}
